### ISSUE TITLE
Any chance to push the .npz file to run sweeps on compas Dataset ? 

### ISSUE THREAD

**Issue by jctaillandier** [ecreager/laftr#2]
Alternatively, specifying the format the data should have to be able to reproduce with compas data. Cheers

**Comment by ecreager** [comment]
We did not perform COMPAS experiments in our paper so the dataset is not supported by this repo. If you are interested in data loaders for that dataset you could check out this repo: https://github.com/algofairness/fairness-comparison (accompanies this paper - https://arxiv.org/pdf/1802.04422.pdf)
